    $(document).ready(function(){
        $("select").change(function(){
            $("select option:selected").each(function(){
                if($(this).attr("value")==1){
 		    $("*").show();
		    $("*").attr("required",true);
		    $("#requestOf").removeAttr("required");
                    $("#commissions").removeAttr("required");
                    $("#requestOf").hide();
                    $("#commissions").hide();
                }
                if($(this).attr("value")==2){
                    $("*").show();
		    $("*").attr("required",true);
		    $("#bfc").removeAttr("required");
		    $("#commissions").removeAttr("required");
                    $("#bfc").hide();
                    $("#commissions").hide();
                }
                if($(this).attr("value")==3){
                    $("*").show();
		    $("*").attr("required",true);
		    $("#requestOf").removeAttr("required");
		    $("#commissions").removeAttr("required");
		    $("#bfc").removeAttr("required");
		    $("#salary").removeAttr("required");
                    $("#requestOf").hide();
                    $("#commissions").hide();
                    $("#bfc").hide();
                    $("#salary").hide();
                }
                if($(this).attr("value")==4){
                    $("*").show();
		    $("*").attr("required",true);
		    $("#requestOf").removeAttr("required");
		    $("#bfc").removeAttr("required");
		    $("#salary").removeAttr("required");
                    $("#requestOf").hide();
                    $("#bfc").hide();
                    $("#salary").hide();
                }
                if($(this).attr("value")==""){
		    $("*").attr("required",true);
                    $("*").show();
                }
            });
        }).change();
    });

	
